# Generated by Django 3.1.7 on 2021-05-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.IntegerField()),
                ('e_name', models.CharField(max_length=100)),
                ('e_message', models.TextField()),
                ('e_time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
