# Generated by Django 3.1.7 on 2021-05-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroupList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True)),
                ('time_created', models.TimeField(auto_now=True)),
                ('admin_name', models.CharField(max_length=100)),
                ('member_name', models.CharField(max_length=1500)),
                ('group_name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, help_text='description of the group')),
                ('mute_notifications', models.BooleanField(default=False, help_text='disable notification if true')),
                ('icon', models.ImageField(blank=True, help_text='Group icon', upload_to='chartgroup')),
            ],
        ),
        migrations.AddField(
            model_name='textmessage',
            name='e_groupid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
