# Generated by Django 3.1.7 on 2021-05-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210531_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnetoOneMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.IntegerField()),
                ('e_name', models.CharField(max_length=100)),
                ('e_message', models.TextField()),
                ('e_time', models.TimeField(auto_now=True)),
                ('e_groupid', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='TextMessage',
            new_name='GroupMessage',
        ),
    ]
