# Generated by Django 3.1.7 on 2021-07-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
    ]
