# Generated by Django 3.1.7 on 2021-05-04 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatewiseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('week', models.CharField(max_length=50)),
                ('time_in', models.CharField(max_length=50)),
                ('time_out', models.CharField(max_length=50)),
                ('work_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserDayoffData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hr_approval', models.CharField(max_length=100)),
                ('tl_approval', models.CharField(max_length=100)),
                ('leave_reason', models.TextField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('encod_image', models.CharField(max_length=2500)),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=200)),
                ('emp', models.CharField(max_length=100)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='attendance.attendancemodel')),
            ],
        ),
    ]
