# Generated by Django 3.1.7 on 2021-05-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdayoffdata',
            name='leave_reasons',
            field=models.TextField(default=1, max_length=1500),
            preserve_default=False,
        ),
    ]
