# Generated by Django 3.1.7 on 2021-05-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdayoffdata',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='userdayoffdata',
            name='start_date',
        ),
    ]
