# Generated by Django 3.1.7 on 2021-05-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20210504_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidaydata',
            old_name='day_name',
            new_name='occasion',
        ),
    ]
