# Generated by Django 3.1.7 on 2021-05-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_userdayoffdata_leave_reasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdayoffdata',
            name='leave_reasons',
        ),
    ]
