# Generated by Django 3.1.7 on 2021-06-06 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0007_delete_timesheetdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('start_time', models.TimeField(auto_now=True)),
                ('finish_time', models.TimeField(auto_now=True)),
                ('total_time', models.TimeField(auto_now=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
