# Generated by Django 3.1.7 on 2021-06-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20210606_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetdata',
            name='finish_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timesheetdata',
            name='total_time',
            field=models.TimeField(null=True),
        ),
    ]
