# Generated by Django 3.1.7 on 2021-06-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_timesheetdata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetdata',
            name='finish_time',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesheetdata',
            name='start_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='timesheetdata',
            name='total_time',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
